{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "opsdeck.postgresql.fullname" . }}
  labels:
    {{- include "opsdeck.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "opsdeck.postgresql.selectorLabels" . | nindent 4 }}
{{- end }}
